
GLOBAL:
   PREFIX:
      PREFIX: "&e&lHytaria &6&l×"
      ERROR_PREFIX: "&4&l(!)"
      
   WEBSITE: "www.hytaria.fr"

   # ---------------------------------------- #

DISCORD:
   TOKEN: 
   
   PREFIX: "."
   STATUS: "ONLINE"
   
   ACTIVITY:
      TYPE: "WATCHING"
      MESSAGE: "{DISCORD_PREFIX}help | {WEBSITE}"
      
EMOTE:
   CUSTOM_CHAT: "<:chat:949406454266339398>"