
GLOBAL:
   PREFIX:
      PREFIX: "&e&lHytaria &6&l√ó"
      ERROR_PREFIX: "&4&l(!)"
      
   WEBSITE: "www.hytaria.fr"

   # ---------------------------------------- #

DISCORD:
   TOKEN: 
   
   PREFIX: "."
   STATUS: "ONLINE"
   
   ACTIVITY:
      TYPE: "WATCHING"
      MESSAGE: "{DISCORD_PREFIX}help | {WEBSITE}"
      
   # ---------------------------------------- #

CHANNEL:
   NAME:
   
         # ---- CATEGORY : LOGS ---- #
   
      LOGS_GLOBAL: "üìÑ‚îÉ…¢lobal"
      LOGS_CHAT: "üìÑ‚îÉ·¥Ñhat"
      LOGS_SERVEUR: "üìÑ‚îÉserveur"
      LOGS_MODERATION: "üìÑ‚îÉ·¥çod√©ration"
      LOGS_DEVELOPPEMENT: "üìÑ‚îÉ·¥Ö√©veloppement"
   ID:
   
         # ---- CATEGORY : LOGS ---- #
         
      LOGS_GLOBAL: 949276801350393897
      LOGS_CHAT: 984410313879322644
      LOGS_SERVEUR: 995654241081364492
      LOGS_MODERATION: 946799695651549205
      LOGS_DEVELOPPEMENT: 984410365985193996

EMOTE:
   CUSTOM_CHAT: "<:chat:949406454266339398>"